//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touch1File.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Touch1File.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name is missing from the command line..
        /// </summary>
        internal static string ERRMSG_FILE_NAME_MISSING {
            get {
                return ResourceManager.GetString("ERRMSG_FILE_NAME_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified input file cannot be found..
        /// </summary>
        internal static string ERRMSG_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERRMSG_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy/MM/dd HH:mm:ss.
        /// </summary>
        internal static string FILETIME_FORMAT {
            get {
                return ResourceManager.GetString("FILETIME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastWriteTime of File {0} {1}.
        /// </summary>
        internal static string LOGMSG_FILE_TOUCH_OUTCOME {
            get {
                return ResourceManager.GetString("LOGMSG_FILE_TOUCH_OUTCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated.
        /// </summary>
        internal static string LOGMSG_FILE_TOUCH_SUCCESSFUL {
            get {
                return ResourceManager.GetString("LOGMSG_FILE_TOUCH_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update FAILED, leaving LastWriteTime UNCHANGED.
        /// </summary>
        internal static string LOGMSG_FILE_TOUCH_UNSUCCESSFUL {
            get {
                return ResourceManager.GetString("LOGMSG_FILE_TOUCH_UNSUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File Current LastWriteTime = {0}.
        /// </summary>
        internal static string LOGMSG_INPUT_FILE_CURR_DATE {
            get {
                return ResourceManager.GetString("LOGMSG_INPUT_FILE_CURR_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File Revised LastWriteTime = {0}{1}.
        /// </summary>
        internal static string LOGMSG_INPUT_FILE_NEW_DATE {
            get {
                return ResourceManager.GetString("LOGMSG_INPUT_FILE_NEW_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File Name                  = {0}{1}.
        /// </summary>
        internal static string LOGMSG_SPECIFIED_INPUT_FILENAME {
            get {
                return ResourceManager.GetString("LOGMSG_SPECIFIED_INPUT_FILENAME", resourceCulture);
            }
        }
    }
}
