//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touch1File.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Touch1File.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return after default wait time of {0} seconds.
        /// </summary>
        internal static string CMD_ARG_MSG_DEFAULT_WAIT {
            get {
                return ResourceManager.GetString("CMD_ARG_MSG_DEFAULT_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action on Program Termination    = {0} ({1}).
        /// </summary>
        internal static string CMD_ARG_MSG_HOW2EXIT {
            get {
                return ResourceManager.GetString("CMD_ARG_MSG_HOW2EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy behavior - Wait until the operator presses the ENTEER (RETURN) key..
        /// </summary>
        internal static string CMD_ARG_MSG_UNSPECIFIED {
            get {
                return ResourceManager.GetString("CMD_ARG_MSG_UNSPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait until the operator presses the ENTEER (RETURN) key..
        /// </summary>
        internal static string CMD_ARG_MSG_WAIT_CARBON {
            get {
                return ResourceManager.GetString("CMD_ARG_MSG_WAIT_CARBON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in seconds to wait          = {0}{1}.
        /// </summary>
        internal static string CMD_ARG_MSG_WAIT_DURATION {
            get {
                return ResourceManager.GetString("CMD_ARG_MSG_WAIT_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return control immediately to the script or OS..
        /// </summary>
        internal static string CMD_ARG_MSG_WAIT_NONE {
            get {
                return ResourceManager.GetString("CMD_ARG_MSG_WAIT_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return after time specified by {0} switch ({1} seconds)..
        /// </summary>
        internal static string CMD_ARG_MSG_WAIT_TIME {
            get {
                return ResourceManager.GetString("CMD_ARG_MSG_WAIT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how2wait.
        /// </summary>
        internal static string CMDARG_HOW2WAIT {
            get {
                return ResourceManager.GetString("CMDARG_HOW2WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsp.
        /// </summary>
        internal static string CMDARG_UNSPECIFIED {
            get {
                return ResourceManager.GetString("CMDARG_UNSPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait.
        /// </summary>
        internal static string CMDARG_WAIT_TILL {
            get {
                return ResourceManager.GetString("CMDARG_WAIT_TILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carb.
        /// </summary>
        internal static string CMDARG_WAITCARBON {
            get {
                return ResourceManager.GetString("CMDARG_WAITCARBON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cont.
        /// </summary>
        internal static string CMDARG_WAITNONE {
            get {
                return ResourceManager.GetString("CMDARG_WAITNONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waittime.
        /// </summary>
        internal static string CMDARG_WAITTIME {
            get {
                return ResourceManager.GetString("CMDARG_WAITTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name is missing from the command line..
        /// </summary>
        internal static string ERRMSG_FILE_NAME_MISSING {
            get {
                return ResourceManager.GetString("ERRMSG_FILE_NAME_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified input file cannot be found..
        /// </summary>
        internal static string ERRMSG_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERRMSG_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy/MM/dd HH:mm:ss.
        /// </summary>
        internal static string FILETIME_FORMAT {
            get {
                return ResourceManager.GetString("FILETIME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastWriteTime of File {0} {1}.
        /// </summary>
        internal static string LOGMSG_FILE_TOUCH_OUTCOME {
            get {
                return ResourceManager.GetString("LOGMSG_FILE_TOUCH_OUTCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated.
        /// </summary>
        internal static string LOGMSG_FILE_TOUCH_SUCCESSFUL {
            get {
                return ResourceManager.GetString("LOGMSG_FILE_TOUCH_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update FAILED, leaving LastWriteTime UNCHANGED.
        /// </summary>
        internal static string LOGMSG_FILE_TOUCH_UNSUCCESSFUL {
            get {
                return ResourceManager.GetString("LOGMSG_FILE_TOUCH_UNSUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File Current LastWriteTime = {0}.
        /// </summary>
        internal static string LOGMSG_INPUT_FILE_CURR_DATE {
            get {
                return ResourceManager.GetString("LOGMSG_INPUT_FILE_CURR_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File Revised LastWriteTime = {0}{1}.
        /// </summary>
        internal static string LOGMSG_INPUT_FILE_NEW_DATE {
            get {
                return ResourceManager.GetString("LOGMSG_INPUT_FILE_NEW_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File Name                  = {0}{1}.
        /// </summary>
        internal static string LOGMSG_SPECIFIED_INPUT_FILENAME {
            get {
                return ResourceManager.GetString("LOGMSG_SPECIFIED_INPUT_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (per command line).
        /// </summary>
        internal static string MSG_WAIT_PER_CMDARG {
            get {
                return ResourceManager.GetString("MSG_WAIT_PER_CMDARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (per programmed default).
        /// </summary>
        internal static string MSG_WAIT_PER_DEFAULT {
            get {
                return ResourceManager.GetString("MSG_WAIT_PER_DEFAULT", resourceCulture);
            }
        }
    }
}
